### PR TITLE
Fix: remove hardcoded models

### LINKED ISSUE #167: Bug - default models are used even when user selects custom models
Hi!

There's a bug where default model is used even if user selects other models. I found that it is firstPhaseImplementation, phaseImplementation and realtimeCodeFixer agents that always use the default models.

### PR DESCRIPTION
**Pull request by timekone**
Hi!

I've found a bug where a default model is used even if user selects other models. I found that it is firstPhaseImplementation, phaseImplementation and fileRegeneration agents that always use the default model.

With this fix, instead of choosing one of default configs for phaseImplementation, we choose agentActionName. Then, inside executeInference the correct model is used.

To fix fileRegeneration I removed modelConfigOverride from RealtimeCodeFixer and replaced it with agentActionNameOverride which is passed to executeInference.

Resolves #167

### CODE REVIEW

File: worker/agents/operations/FileRegeneration.ts [hunk 1]
```diff
@@ -113,7 +112,7 @@ export class FileRegenerationOperation extends AgentOperation<FileRegenerationIn
     ): Promise<FileGenerationOutputType> {
         try {
             // Use realtime code fixer to fix the file with enhanced surgical fix prompts
-            const realtimeCodeFixer = new RealtimeCodeFixer(options.env, options.inferenceContext, false, undefined, AGENT_CONFIG.fileRegeneration, SYSTEM_PROMPT, USER_PROMPT);
+            const realtimeCodeFixer = new RealtimeCodeFixer(options.env, options.inferenceContext, false, undefined, undefined, SYSTEM_PROMPT, USER_PROMPT);
```
Comment (AshishKumar4) [inline worker/agents/operations/FileRegeneration.ts]: This change doesn't affect the real time code fixer, but instead the file regeneration operation. 
File regeneration is used in code reviewing phases and is separate, but under the hood uses the same assistant class of realtime code fixer to make changes but with custom prompts. We supply AGENT_CONFIG.fileRegeneration to make sure the agent config of file regeneration is actually used there instead of realtime code fixer's
The actual bug is in the file realtimeCodeFixer.ts - It should take agent action name as an optional argument in the constructor, and override the action name in executeInference call

File: worker/agents/operations/PhaseImplementation.ts [hunk 2]
```diff
@@ -475,20 +474,16 @@ export class PhaseImplementationOperation extends AgentOperation<PhaseImplementa
     
         const fixedFilePromises: Promise<FileOutputType>[] = [];
 
-        let modelConfig = AGENT_CONFIG.phaseImplementation;
-        if (inputs.isFirstPhase) {
-            modelConfig = AGENT_CONFIG.firstPhaseImplementation;
-        }
+        const agentActionName = inputs.isFirstPhase ? 'firstPhaseImplementation' : 'phaseImplementation';
```
Comment (AshishKumar4) [inline worker/agents/operations/PhaseImplementation.ts:477]: I was actually planning on removing the need for first phase implementation logic itself.
But I guess this works too.

**Comment by AshishKumar4** [comment]
Thanks for raising the PRs, the realtime code fixer thing is indeed a bug but the root cause is different as I have commented.
And about the phase implementation thing - it looks good. The phase implementation was indeed using hard coded config override. The fix itself is right, but I would suggest not altering the model configuration for phase implementation on the official deployed version at build.cloudflare.dev, because officially, we are only supporting gemini models for free tier. And gemini 2.5 pro with low reasoning works best with the current setup for this operation. However with a custom deployment, you are free to use any other model and thus choose different configs.

File: worker/agents/operations/FileRegeneration.ts (hunk 1 above)
Comment (timekone) [reply worker/agents/operations/FileRegeneration.ts]: Yes! Sorry, I mixed up realtimeCodeFixer and fileRegeneration in the description. 😅 
Thank you for the review! Yeah, now I see that my changes make fileRegeneration use realtimeCodeFixer's config. I will add an optional agentActionName argument to RealtimeCodeFixer's constructor and pass it to executeInference.

Still, if we supply AGENT_CONFIG.fileRegeneration here, in realtimeCodeFixer.ts it is passed down to `executeInference()`. And in that case, in executeInference the initial default config of fileRegeneration is used instead of user's choice. 
So instead, I think I should pass agentActionName as mentioned earlier, but remove modelConfigOverride from RealtimeCodeFixer's constructor. This way fileRegeneration's config will be picked inside executeInference.
Does this make sense?

**Comment by AshishKumar4** [comment]
LGTM, merging to nightly
